name: CI/CD Pipeline for devops-take-home assessment

on:
  push:
    branches:
      - main
      - test  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests using Jest  
        run: npm test

      - name: Build and push Docker image
        run: |
          docker build -t iamguil/devops-take-home .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag iamguil/devops-take-home iamguil/test-repo:latest
          docker push iamguil/test-repo:latest
